package org.wikipathways.wp2rdf.ontologies;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/tina/workspace/WpVocabularies/OWL/WP.rdf 
 * @author Auto-generated by schemagen on 03 Jun 2015 11:06 
 */
public class Wp {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vocabularies.wikipathways.org/wp#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property isAbout = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#isAbout" );
    
    public static final Property ontologyTag = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#ontologyTag" );
    
    public static final Property organism = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#organism" );
    
    public static final Property organismName = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#organismName" );
    
    public static final Property participants = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#participants" );
    
    public static final Property publicationReference = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#publicationReference" );
    
    public static final Property source = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#source" );
    
    public static final Property target = m_model.createProperty( "http://vocabularies.wikipathways.org/wp#target" );
    
    public static final Resource Binding = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Binding" );
    
    public static final Resource Catalysis = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Catalysis" );
    
    public static final Resource Complex = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Complex" );
    
    public static final Resource ComplexBinding = m_model.createResource( "http://vocabularies.wikipathways.org/wp#ComplexBinding" );
    
    public static final Resource Conversion = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Conversion" );
    
    public static final Resource DataNode = m_model.createResource( "http://vocabularies.wikipathways.org/wp#DataNode" );
    
    public static final Resource DirectedInteraction = m_model.createResource( "http://vocabularies.wikipathways.org/wp#DirectedInteraction" );
    
    public static final Resource GeneProduct = m_model.createResource( "http://vocabularies.wikipathways.org/wp#GeneProduct" );
    
    public static final Resource Inhibition = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Inhibition" );
    
    public static final Resource Interaction = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Interaction" );
    
    public static final Resource Metabolite = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Metabolite" );
    
    public static final Resource Pathway = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Pathway" );
    
    public static final Resource Protein = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Protein" );
    
    public static final Resource Rna = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Rna" );
    
    public static final Resource Stimulation = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Stimulation" );
    
    public static final Resource TranscriptionTranslation = m_model.createResource( "http://vocabularies.wikipathways.org/wp#TranscriptionTranslation" );
    
    public static final Resource University = m_model.createResource( "http://vocabularies.wikipathways.org/wp#Maastricht%20University" );
    
    public static final Resource mkutmon = m_model.createResource( "http://vocabularies.wikipathways.org/wp#mkutmon" );
    
    public static final Resource ryan = m_model.createResource( "http://vocabularies.wikipathways.org/wp#ryan" );
    
}