prefix dcterms: <http://purl.org/dc/terms/>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix foaf:    <http://xmlns.com/foaf/0.1/> 
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
	?item a wp:Pathway ;
		dc:title ?title ; 
		wp:organism ?organism_uri ; 
		foaf:page ?page ;
		dc:identifier ?identifier . 
        ?metabolite dcterms:isPartOf ?item ;
                a wp:Metabolite ;
                dc:identifier ?pw_uri .
	?item wp:organismName ?organism . 
	OPTIONAL { ?item dcterms:description ?description }
	OPTIONAL { ?item wp:ontologyTag ?ontology }
}